### ISSUE TITLE
Can createResource's url param be a function please ?

### ISSUE THREAD

**Issue by peritus** [mgcrea/redux-rest-resource#7]
First: Thanks for this library, it comes very close to how I like to handle rest resources and seems the least opinionated / most flexible library I've found for redux + REST so far.

I'm trying to fit my existing, hand-written action creators into this and I have a resource that is available at two URLs (one super-heavy server-side cached, public, read-only .. the other one not cached, only available to the user who has write access to it).

I need more flexibility regarding the url building.

-----

Idea is the following:

Would it be possible to change `createResource`'s `url` option so that it could also be a function so that I can do the url-building myself ?

Taking your example from the docs to illustrate a bit:

```
export const {types, actions, reducers} = createResource({
  name: 'user',
  url: ({urlParams, context, stripTrailingSlashes}) => {
    return `${hostUrl}/users/:id?apiKey=${apiKey}`
  }
});
```

Maybe even make the return value be either

* a string -> final URL that will be passed to `fetch`
* an object `{url, urlParams, context, stripTrailingSlashes}` so that users of the library don't have to re-implement half of `buildFetchUrl`

?

**Comment by mgcrea** [comment]
Hey, thank you for you nice feedback.

Sounds like a useful use-case, might have the time to tackle this pretty soon or do you want to work on a PR?

Another quick question since you are interested in the subject, I was (and I'm still) wondering on the actions naming scheme:

1. `actions.fetchUsers()`
or
1. `actions.fetch()`.

Currently I went for `1.` which enable easy merging of multiple sets of actions (`actions.fetchUsers`, `actions.fetchDevices`, etc.) on the same object. But now I'm considering `2.`, since suffixes could easily be added at the  `connect` stage, and would allow for a way simpler code (in the lib), and potentially easier code re-use in your app (as the suffix scheme would now be opt-in).

I'm leaning towards refactoring this but I don't like the idea of breaking API.

For survey purposes, do you have a personal preference on this?

**Comment by peritus** [comment]
Thanks for the quick reply!

Regarding `url: function() ...`:

I think the hard part here is finding a good API that is consistent with the rest of this library, implementation wise it's probably relatively straight forward, not ? I don't think I'm qualified (yet) as I just discovered this library a few hours ago. That might change the more I use it and I might send PRs then :)

**Comment by peritus** [comment]
Regarding `actions.fetchUsers()` vs `actions.fetch()`:

In my pet project I now created a file called `resources/User.js` which I import like this:

```
import { actions as userActions } from './resources/User';
```

and then use it like this:

```
dispatch(userActions.getUser(ownProps.routeParams.profileId))
  .then(...)
```

-> which contains the word _user_ twice :(

So, I think I'd prefer option (2) because it feels less redundant. Also, if you start documenting it like this, it helps with code organisation (1 resource per file) which I think is desirable.

However, that would probably make what you describe in _You can combine multiple resources_ more difficult (unsure how that works, would have to dig in deeper).

As for breaking the API, here's how I would do/expect it: Release a new version that contains the new way, document the new way, still support the old way but don't promote it anymore. Then, 6 months from now hard-deprecate it by removing the old way, using bold text in the release notes and throw an error if someone is using the old way with pointing to a migration guide on http://mgcrea.github.io/redux-rest-resource/ ..

**Comment by peritus** [comment]
> suffixes could easily be added at the connect stage

.. or during `export` from the module containing the `createResource` call ..

**Comment by peritus** [comment]
> I think the hard part here is finding a good API

Any thoughts on this one?
